modLoader = "javafml" #mandatory
loaderVersion = "[45,)" #mandatory
license = "MIT"
[[mods]] #mandatory
modId = "spawnvisualizer" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "SpawnVisualizer" #mandatory
description = '''

'''

[[dependencies.spawnvisualizer]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[45,)" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.spawnvisualizer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"
